import numpy as np

# create 1-D array
x = np.random.rand(10)
print(x)

# standard list indexing on arrays
print(x[0])
print(x[0:3])
print(x[-3])

# index an array with a list of indices
ind = [2,4,7]
print(x[ind])

# index with a boolean mask
mask = [True, True, True, False, False, False, False, False, False, False]
print(x[mask])
# this is identical to
print(x[[0,1,2]])

# generate a boolean mask
print( x>0.5 )

# index an array with a boolean mask generated by a condition
print( x[x>0.5] )

# this will fail because you can't perform 'and' on arrays
# print(x[ x>0.2 and x<0.8 ])

# you can still do it like this
print( x[ np.logical_and(x>0.2,x<0.8) ] )

# you can also do it like this
y = x[x>0.2]
y = y[y<0.8]
print(y)

# # create 2-D array
# x = np.random.rand(5,5)
# print(x)

# # get the element on the 2nd row, 3rd column
# print(x[2,3])

# # get the entire 2nd row
# print(x[2,:])

# # get the entire 3rd column
# print(x[:,3])


print( np.ones(5)+np.ones(4) )



